-- ITEM_TREE에서 PARENT_ITEM_ID IS NULL인 ITEM_ID들을 골라낸다.
-- 그 ITEM_ID들의 이름(ITEM_NAME)이 필요하니, ITEM_INFO와 조인(또는 서브쿼리)해서 이름을 가져온다.
-- ITEM_ID 기준 오름차순 정렬.

SELECT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO I
INNER JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID ASC;