SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT * p.PRICE) as TOTALSALES
FROM FOOD_ORDER o LEFT JOIN FOOD_PRODUCT p
ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m")='2022-05'
GROUP BY p.PRODUCT_ID
ORDER BY TOTALSALES DESC, p.PRODUCT_ID;

