-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, A.REPLY_ID, A.WRITER_ID, A.CONTENTS,
       DATE_FORMAT(A.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY A
WHERE B.BOARD_ID = A.BOARD_ID AND B.CREATED_DATE LIKE '%2022-10%'
ORDER BY A.CREATED_DATE, B.TITLE;