SELECT MAX_PRICES.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS MAX_PRICES
JOIN FOOD_PRODUCT ON MAX_PRICES.CATEGORY = FOOD_PRODUCT.CATEGORY AND MAX_PRICES.MAX_PRICE = FOOD_PRODUCT.PRICE
ORDER BY MAX_PRICE DESC;